deploy:
  - config.ini
  - deploy.sh

preface:
  - chapter_preface/*

install:
  - chapter_install/*

tools:
  - chapter_introduction/*

introduction:
    - chapter_appendix-tools-for-deep-learning/*

math:
    - chapter_appendix_math/*

preliminaries:
    - chapter_preliminaries/*

utility:
  - utils.py
  - test_utils.py
  - tests/*

glosssary:
  - glossary.md
